@host=http://localhost:5080

### GET all users
GET {{host}}/users

### GET user by id
GET {{host}}/users/e22b093d-e9bf-47f9-933d-930fda238fe0

### POST a user
POST {{host}}/users
Content-Type: application/json

{
  "FirstName": "Yanni",
  "LastName": "Alshoufi"
}